apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-synchronizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-synchronizer
  template:
    metadata:
      labels:
        app: data-synchronizer
    spec:
      containers:
        - name: data-synchronizer
          image: ghcr.io/saetch/github_visualizer_data_synchronizer:latest
          imagePullPolicy: Always