apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-enricher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-enricher
  template:
    metadata:
      labels:
        app: data-enricher
    spec:
      containers:
        - name: data-enricher
          image: ghcr.io/saetch/github_visualizer_data_enricher:latest
          imagePullPolicy: Always