apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/saetch/github_visualizer_frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: preprocessed-data
              mountPath: /data
      volumes:
        - name: preprocessed-data
          persistentVolumeClaim:
            claimName: preprocessed-data