apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
        - name: websocket-server
          image: ghcr.io/saetch/github_visualizer_websocket_server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
