name: Build Images
run-name: ${{ github.actor }} 
on:
  push:
    branches:
      - main

jobs:
  docker-images:
    runs-on: Ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
    - uses: actions/checkout@v5
    - run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
    - run: docker compose -f docker-compose.yml build
    - uses: actions/delete-package-versions@v5
      with:
          package-name: 'ghcr.io/saetch/github_visualizer_preprocessor'
          package-type: container
          min-versions-to-keep: 1
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'ghcr.io/saetch/github_visualizer_archive_reader'
        package-type: container
        min-versions-to-keep: 1
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'ghcr.io/saetch/github_visualizer_data_enricher'
        package-type: container
        min-versions-to-keep: 1
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'ghcr.io/saetch/github_visualizer_data_synchronousizer'
        package-type: container
        min-versions-to-keep: 1
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'ghcr.io/saetch/github_visualizer_websocket_server'
        package-type: container
        min-versions-to-keep: 1
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'ghcr.io/saetch/github_visualizer_sampler'
        package-type: container
        min-versions-to-keep: 1
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'ghcr.io/saetch/github_visualizer_frontend'
        package-type: container
        min-versions-to-keep: 1
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'ghcr.io/saetch/github_visualizer_nats'
        package-type: container
        min-versions-to-keep: 1
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'ghcr.io/saetch/github_visualizer_nats'
        package-type: container
        min-versions-to-keep: 1
    - run: docker compose -f ./docker-compose.yml push

